[build]
jobs = 8

[env]
LIBCLANG_PATH = "C:\\Program Files\\LLVM\\bin"
CUDA_PATH = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2"
CUDA_HOME = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2"
CUDAToolkit_ROOT = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2"
CudaToolkitDir = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2\\"
CUDACXX = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2\\bin\\nvcc.exe"
CUDARC_CUDA_VERSION = "13020"
CUDA_COMPUTE_CAP = "75"
CUDA_EXTRA_COMPUTE_CAPS = "80,86,89,120,121"
CMAKE_CUDA_ARCHITECTURES = "75-virtual;80-virtual;86-real;89-real;120-real;121-real"
GGML_NATIVE = "OFF"
NVCC_CCBIN = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.44.35207\\bin\\Hostx64\\x64\\cl.exe"
